// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zdyfapi) DeepCopyInto(out *Zdyfapi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zdyfapi.
func (in *Zdyfapi) DeepCopy() *Zdyfapi {
	if in == nil {
		return nil
	}
	out := new(Zdyfapi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Zdyfapi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZdyfapiList) DeepCopyInto(out *ZdyfapiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Zdyfapi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZdyfapiList.
func (in *ZdyfapiList) DeepCopy() *ZdyfapiList {
	if in == nil {
		return nil
	}
	out := new(ZdyfapiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZdyfapiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZdyfapiService) DeepCopyInto(out *ZdyfapiService) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZdyfapiService.
func (in *ZdyfapiService) DeepCopy() *ZdyfapiService {
	if in == nil {
		return nil
	}
	out := new(ZdyfapiService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZdyfapiSpec) DeepCopyInto(out *ZdyfapiSpec) {
	*out = *in
	if in.NameReplicas != nil {
		in, out := &in.NameReplicas, &out.NameReplicas
		*out = new(int32)
		**out = **in
	}
	if in.NameSports != nil {
		in, out := &in.NameSports, &out.NameSports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	if in.DataReplicas != nil {
		in, out := &in.DataReplicas, &out.DataReplicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZdyfapiSpec.
func (in *ZdyfapiSpec) DeepCopy() *ZdyfapiSpec {
	if in == nil {
		return nil
	}
	out := new(ZdyfapiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZdyfapiStatus) DeepCopyInto(out *ZdyfapiStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZdyfapiStatus.
func (in *ZdyfapiStatus) DeepCopy() *ZdyfapiStatus {
	if in == nil {
		return nil
	}
	out := new(ZdyfapiStatus)
	in.DeepCopyInto(out)
	return out
}
