// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"zdyfop/pkg/apis/zdyf/v1alpha1.Zdyfapi":       schema_pkg_apis_zdyf_v1alpha1_Zdyfapi(ref),
		"zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiSpec":   schema_pkg_apis_zdyf_v1alpha1_ZdyfapiSpec(ref),
		"zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiStatus": schema_pkg_apis_zdyf_v1alpha1_ZdyfapiStatus(ref),
	}
}

func schema_pkg_apis_zdyf_v1alpha1_Zdyfapi(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Zdyfapi is the Schema for the zdyfapis API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiSpec", "zdyfop/pkg/apis/zdyf/v1alpha1.ZdyfapiStatus"},
	}
}

func schema_pkg_apis_zdyf_v1alpha1_ZdyfapiSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZdyfapiSpec defines the desired state of Zdyfapi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_zdyf_v1alpha1_ZdyfapiStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZdyfapiStatus defines the observed state of Zdyfapi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
